### ISSUE TITLE
参考线没有自动吸附的功能

### ISSUE THREAD

**Issue by chenminmin199300** [yyccmmkk/js-reference-line#1]
作者大大，有考虑增加一个div靠近时显示参考线，并同时可以自动吸附功能吗？

**Comment by yyccmmkk** [comment]
考虑过，可以加入开发计划

**Comment by yyccmmkk** [comment]
> 
> 
> 作者大大，有考虑增加一个div靠近时显示参考线，并同时可以自动吸附功能吗？

加入开发计划，并且还有很多待完善的，
